/home/jmn/bsim_2/minisat/core/Solver.o /home/jmn/bsim_2/minisat/core/Solver.or /home/jmn/bsim_2/minisat/core/Solver.od /home/jmn/bsim_2/minisat/core/Solver.op: /home/jmn/bsim_2/minisat/core/Solver.cc \
 /home/jmn/bsim_2/minisat/core/../mtl/Alg.h \
 /home/jmn/bsim_2/minisat/core/../mtl/../mtl/Vec.h \
 /home/jmn/bsim_2/minisat/core/../mtl/../mtl/../mtl/IntTypes.h \
 /home/jmn/bsim_2/minisat/core/../mtl/../mtl/../mtl/XAlloc.h \
 /home/jmn/bsim_2/minisat/core/../mtl/Sort.h \
 /home/jmn/bsim_2/minisat/core/../utils/System.h \
 /home/jmn/bsim_2/minisat/core/../utils/../mtl/IntTypes.h \
 /home/jmn/bsim_2/minisat/core/../core/Solver.h \
 /home/jmn/bsim_2/minisat/core/../core/../mtl/Vec.h \
 /home/jmn/bsim_2/minisat/core/../core/../mtl/Heap.h \
 /home/jmn/bsim_2/minisat/core/../core/../mtl/../mtl/Vec.h \
 /home/jmn/bsim_2/minisat/core/../core/../mtl/../mtl/IntMap.h \
 /home/jmn/bsim_2/minisat/core/../core/../mtl/../mtl/../mtl/Vec.h \
 /home/jmn/bsim_2/minisat/core/../core/../mtl/Alg.h \
 /home/jmn/bsim_2/minisat/core/../core/../mtl/IntMap.h \
 /home/jmn/bsim_2/minisat/core/../core/../utils/Options.h \
 /home/jmn/bsim_2/minisat/core/../core/../utils/../mtl/IntTypes.h \
 /home/jmn/bsim_2/minisat/core/../core/../utils/../mtl/Vec.h \
 /home/jmn/bsim_2/minisat/core/../core/../utils/../utils/ParseUtils.h \
 /home/jmn/bsim_2/minisat/core/../core/../utils/../utils/../mtl/XAlloc.h \
 /home/jmn/bsim_2/minisat/core/../core/../core/SolverTypes.h \
 /home/jmn/bsim_2/minisat/core/../core/../core/../mtl/IntTypes.h \
 /home/jmn/bsim_2/minisat/core/../core/../core/../mtl/Alg.h \
 /home/jmn/bsim_2/minisat/core/../core/../core/../mtl/Vec.h \
 /home/jmn/bsim_2/minisat/core/../core/../core/../mtl/IntMap.h \
 /home/jmn/bsim_2/minisat/core/../core/../core/../mtl/Map.h \
 /home/jmn/bsim_2/minisat/core/../core/../core/../mtl/../mtl/IntTypes.h \
 /home/jmn/bsim_2/minisat/core/../core/../core/../mtl/../mtl/Vec.h \
 /home/jmn/bsim_2/minisat/core/../core/../core/../mtl/Alloc.h \
 /home/jmn/bsim_2/minisat/core/../core/../core/../mtl/../mtl/XAlloc.h
/home/jmn/bsim_2/minisat/core/Main.o /home/jmn/bsim_2/minisat/core/Main.or /home/jmn/bsim_2/minisat/core/Main.od /home/jmn/bsim_2/minisat/core/Main.op: /home/jmn/bsim_2/minisat/core/Main.cc \
 /home/jmn/bsim_2/minisat/core/../utils/System.h \
 /home/jmn/bsim_2/minisat/core/../utils/../mtl/IntTypes.h \
 /home/jmn/bsim_2/minisat/core/../utils/ParseUtils.h \
 /home/jmn/bsim_2/minisat/core/../utils/../mtl/XAlloc.h \
 /home/jmn/bsim_2/minisat/core/../utils/Options.h \
 /home/jmn/bsim_2/minisat/core/../utils/../mtl/Vec.h \
 /home/jmn/bsim_2/minisat/core/../utils/../mtl/../mtl/IntTypes.h \
 /home/jmn/bsim_2/minisat/core/../utils/../mtl/../mtl/XAlloc.h \
 /home/jmn/bsim_2/minisat/core/../utils/../utils/ParseUtils.h \
 /home/jmn/bsim_2/minisat/core/../core/Dimacs.h \
 /home/jmn/bsim_2/minisat/core/../core/../utils/ParseUtils.h \
 /home/jmn/bsim_2/minisat/core/../core/../core/SolverTypes.h \
 /home/jmn/bsim_2/minisat/core/../core/../core/../mtl/IntTypes.h \
 /home/jmn/bsim_2/minisat/core/../core/../core/../mtl/Alg.h \
 /home/jmn/bsim_2/minisat/core/../core/../core/../mtl/../mtl/Vec.h \
 /home/jmn/bsim_2/minisat/core/../core/../core/../mtl/Vec.h \
 /home/jmn/bsim_2/minisat/core/../core/../core/../mtl/IntMap.h \
 /home/jmn/bsim_2/minisat/core/../core/../core/../mtl/Map.h \
 /home/jmn/bsim_2/minisat/core/../core/../core/../mtl/../mtl/IntTypes.h \
 /home/jmn/bsim_2/minisat/core/../core/../core/../mtl/Alloc.h \
 /home/jmn/bsim_2/minisat/core/../core/../core/../mtl/../mtl/XAlloc.h \
 /home/jmn/bsim_2/minisat/core/../core/Solver.h \
 /home/jmn/bsim_2/minisat/core/../core/../mtl/Vec.h \
 /home/jmn/bsim_2/minisat/core/../core/../mtl/Heap.h \
 /home/jmn/bsim_2/minisat/core/../core/../mtl/../mtl/Vec.h \
 /home/jmn/bsim_2/minisat/core/../core/../mtl/../mtl/IntMap.h \
 /home/jmn/bsim_2/minisat/core/../core/../mtl/Alg.h \
 /home/jmn/bsim_2/minisat/core/../core/../mtl/IntMap.h \
 /home/jmn/bsim_2/minisat/core/../core/../utils/Options.h
